# Generated by Django 4.2.6 on 2023-11-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subTitle', models.CharField(max_length=64)),
                ('body', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='', width_field=100)),
            ],
        ),
    ]
